[manager]
shell = "zsh"


[opener]
new-terminal = [
	{run = 'kitty -d "$1"', orphan = true, for = "unix"},
	# {run = 'zathura "$1"', orphan = true, for = "unix"},
]

[open]
prepend_rules = [
	{mime = "inode/directory", use = 'new-terminal'},
	# {name = "*.pdf", use = 'pdfopener'},
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[plugin]
prepend_preloaders = [
  { mime = "*.3mf", run = "f3d-preview" },
  { mime = "*.obj", run = "f3d-preview" },
  { mime = "*.pts", run = "f3d-preview" },
  { mime = "*.ply", run = "f3d-preview" },
  { mime = "application/octet-stream", run = "f3d-preview" },
  { mime = "*.step", run = "f3d-preview" },
  { mime = "*.stp", run = "f3d-preview" },
]

prepend_previewers = [
  { mime = "*.3mf", run = "f3d-preview" },
  { mime = "*.obj", run = "f3d-preview" },
  { mime = "*.pts", run = "f3d-preview" },
  { mime = "*.ply", run = "f3d-preview" },
  { mime = "application/octet-stream", run = "f3d-preview" },
  { mime = "*.step", run = "f3d-preview" },
  { mime = "*.stp", run = "f3d-preview" },
]
