[colors.bright]
black = "0x4D4D4D"
blue = "0xCAA9FA"
cyan = "0x9AEDFE"
green = "0x5AF78E"
magenta = "0xFF92D0"
red = "0xFF6E67"
white = "0xE6E6E6"
yellow = "0xF4F99D"

[colors.normal]
black = "0x000000"
blue = "0xBD93F9"
cyan = "0x8BE9FD"
green = "0x50FA7B"
magenta = "0xFF79C6"
red = "0xFF5555"
white = "0xBFBFBF"
yellow = "0xF1FA8C"

[colors.primary]
background = "0x000000"
foreground = "0x00FF00"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
#family = "JetBrainsMono Nerd Font"
#style = "Regular"

[window]
dynamic_padding = true
opacity = 0.7

[window.padding]
x = 10
y = 10
